# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180514_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
    ]
